import numpy as np

## Former flags

input_height = 108
input_width = input_height
output_height = 64
output_width = output_height
dataset = "celebA"
input_fname_pattern = "*.jpg"
train_size = np.inf
crop = True
train = True
rotate_azimuth = False
rotate_elevation = False

## Main cfg

image_path = "/home/mvasil/data/img_align_celeba"
gpu_id = 0
refresh_rate = 500
batch_size = 32
max_epochs = 2000
emb_input_size = 112
emb_checkpoint = "/home/mvasil/InsightFace-v2/pretrained/BEST_checkpoint_r101.tar"
emb_tf_model = "/home/mvasil/InsightFace-v2/pretrained/embedder.pb"
emb_test = "/home/mvasil/data/emb_test"
emb_dim = 512
epoch_step = 25
z_dim = 32
d_eta = 0.0001
g_eta = 0.0001
beta1 = 0.5
beta2 = 0.999
discriminator = "discriminator_IN_style_res128"
generator = "generator_AdaIN"
view_func = "generate_random_rotation_translation"
train_func = "train_HoloGAN"
build_func = "build_HoloGAN"
style_disc = "true"
sample_z = "uniform"
add_D_noise = "false"
DStyle_lambda = 50.0
lambda_latent = 1.0
lambda_emb = 150.0
ele_low = 70
ele_high = 110
azi_low = 220
azi_high = 320
scale_low = 1.0
scale_high = 1.0
x_low = 0
x_high = 0
y_low = 0
y_high = 0
z_low = 0
z_high = 0
with_translation = "false"
with_scale = "false"
output_dir = "./results/perceptual/q=1e=150zdim=32crop=128style=50"
